# ---------------------------------------------------------------------------------------------------------------------
# CLOUDWATCH OBSERVABILITY — ALARMS + DASHBOARD
# Bespoke observability-as-code for the sgcut platform (ALB + ECS Fargate services + RDS Postgres). Implements the
# README "Not yet included: CloudWatch alarms (5xx / p99 latency / running-task count)" follow-up, plus a single
# operational dashboard.
#
# Kept as a repo-local module (not the community metric-alarm module) because the metric/dimension wiring here is
# specific to this stack: it stitches together the ALB arn_suffix, the ECS ContainerInsights dimensions, and the RDS
# instance id that the sibling live components expose as outputs.
#
# Alarm actions are optional (var.alarm_actions defaults to []), so this validates/plans without requiring an SNS
# topic to exist first — wire a topic ARN in per environment when notifications are wanted.
# ---------------------------------------------------------------------------------------------------------------------

# =====================================================================================================================
# ALARMS
# =====================================================================================================================

# ---- ALB 5xx from the targets (app returned 5xx) --------------------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "alb_target_5xx" {
  alarm_name          = "${var.name_prefix}-alb-target-5xx"
  alarm_description   = "ALB target 5xx responses > ${var.alb_5xx_threshold} over ${var.period}s — the backend/frontend tasks are erroring."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_Target_5XX_Count"
  statistic           = "Sum"
  comparison_operator = "GreaterThanThreshold"
  threshold           = var.alb_5xx_threshold
  period              = var.period
  evaluation_periods  = var.alb_5xx_evaluation_periods
  treat_missing_data  = "notBreaching" # no requests => no 5xx => not an alarm

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
  }

  alarm_actions = var.alarm_actions
  ok_actions    = var.ok_actions
  tags          = var.tags
}

# ---- ALB 5xx generated by the load balancer itself (no healthy targets, 502/503/504) --------------------------------
resource "aws_cloudwatch_metric_alarm" "alb_elb_5xx" {
  alarm_name          = "${var.name_prefix}-alb-elb-5xx"
  alarm_description   = "ALB-generated 5xx responses > ${var.alb_5xx_threshold} over ${var.period}s — no healthy targets / gateway errors."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "HTTPCode_ELB_5XX_Count"
  statistic           = "Sum"
  comparison_operator = "GreaterThanThreshold"
  threshold           = var.alb_5xx_threshold
  period              = var.period
  evaluation_periods  = var.alb_5xx_evaluation_periods
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
  }

  alarm_actions = var.alarm_actions
  ok_actions    = var.ok_actions
  tags          = var.tags
}

# ---- ALB target p99 latency -----------------------------------------------------------------------------------------
resource "aws_cloudwatch_metric_alarm" "alb_p99_latency" {
  alarm_name          = "${var.name_prefix}-alb-p99-latency"
  alarm_description   = "ALB target p99 response time > ${var.alb_p99_latency_threshold}s over ${var.alb_latency_evaluation_periods}x${var.period}s."
  namespace           = "AWS/ApplicationELB"
  metric_name         = "TargetResponseTime"
  extended_statistic  = "p99" # extended_statistic and statistic are mutually exclusive
  comparison_operator = "GreaterThanThreshold"
  threshold           = var.alb_p99_latency_threshold
  period              = var.period
  evaluation_periods  = var.alb_latency_evaluation_periods
  treat_missing_data  = "notBreaching"

  dimensions = {
    LoadBalancer = var.alb_arn_suffix
  }

  alarm_actions = var.alarm_actions
  ok_actions    = var.ok_actions
  tags          = var.tags
}

# ---- ECS running-task count too low (one per service) ---------------------------------------------------------------
# RunningTaskCount lives in the ECS/ContainerInsights namespace (Container Insights is enabled on the cluster). Missing
# data is treated as breaching: if the service stops emitting the metric it almost certainly has no running tasks.
resource "aws_cloudwatch_metric_alarm" "ecs_running_tasks" {
  for_each = toset(var.ecs_service_names)

  alarm_name          = "${var.name_prefix}-ecs-${each.value}-running-tasks-low"
  alarm_description   = "ECS service ${each.value} RunningTaskCount < ${var.ecs_min_running_tasks} — fewer tasks than desired are running."
  namespace           = "ECS/ContainerInsights"
  metric_name         = "RunningTaskCount"
  statistic           = "Minimum"
  comparison_operator = "LessThanThreshold"
  threshold           = var.ecs_min_running_tasks
  period              = var.period
  evaluation_periods  = 1
  treat_missing_data  = "breaching"

  dimensions = {
    ClusterName = var.ecs_cluster_name
    ServiceName = each.value
  }

  alarm_actions = var.alarm_actions
  ok_actions    = var.ok_actions
  tags          = var.tags
}

# =====================================================================================================================
# DASHBOARD
# =====================================================================================================================
locals {
  # ECS per-service metric series (AWS/ECS namespace: service-level CPU/memory utilization).
  ecs_cpu_metrics = [
    for s in var.ecs_service_names :
    ["AWS/ECS", "CPUUtilization", "ClusterName", var.ecs_cluster_name, "ServiceName", s, { label = s }]
  ]
  ecs_mem_metrics = [
    for s in var.ecs_service_names :
    ["AWS/ECS", "MemoryUtilization", "ClusterName", var.ecs_cluster_name, "ServiceName", s, { label = s }]
  ]

  dashboard_body = {
    widgets = [
      # ---- Row 0: ALB traffic + errors ----------------------------------------------------------------------------
      {
        type   = "metric"
        x      = 0
        y      = 0
        width  = 12
        height = 6
        properties = {
          title  = "ALB — Request Count"
          region = var.region
          view   = "timeSeries"
          stat   = "Sum"
          period = 60
          metrics = [
            ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", var.alb_arn_suffix]
          ]
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 0
        width  = 12
        height = 6
        properties = {
          title  = "ALB — 4xx / 5xx Counts"
          region = var.region
          view   = "timeSeries"
          stat   = "Sum"
          period = 60
          metrics = [
            ["AWS/ApplicationELB", "HTTPCode_Target_4XX_Count", "LoadBalancer", var.alb_arn_suffix, { label = "target 4xx" }],
            ["AWS/ApplicationELB", "HTTPCode_Target_5XX_Count", "LoadBalancer", var.alb_arn_suffix, { label = "target 5xx" }],
            ["AWS/ApplicationELB", "HTTPCode_ELB_5XX_Count", "LoadBalancer", var.alb_arn_suffix, { label = "elb 5xx" }]
          ]
        }
      },
      # ---- Row 1: ALB latency p50 / p99 ---------------------------------------------------------------------------
      {
        type   = "metric"
        x      = 0
        y      = 6
        width  = 24
        height = 6
        properties = {
          title  = "ALB — Target Response Time (p50 / p99, overall + per target group)"
          region = var.region
          view   = "timeSeries"
          period = 60
          # Aggregate ALB latency (all targets), then a p99 series per target group so backend vs frontend latency is
          # visible separately. Per-TG metrics carry both the TargetGroup and LoadBalancer dimensions.
          metrics = concat(
            [
              ["AWS/ApplicationELB", "TargetResponseTime", "LoadBalancer", var.alb_arn_suffix, { stat = "p50", label = "alb p50" }],
              ["AWS/ApplicationELB", "TargetResponseTime", "LoadBalancer", var.alb_arn_suffix, { stat = "p99", label = "alb p99" }],
            ],
            [for k, tg in var.target_group_arn_suffixes :
              ["AWS/ApplicationELB", "TargetResponseTime", "TargetGroup", tg, "LoadBalancer", var.alb_arn_suffix, { stat = "p99", label = "${k} p99" }]
            ]
          )
        }
      },
      # ---- Row 2: ECS CPU / memory per service --------------------------------------------------------------------
      {
        type   = "metric"
        x      = 0
        y      = 12
        width  = 12
        height = 6
        properties = {
          title   = "ECS — CPU Utilization (%)"
          region  = var.region
          view    = "timeSeries"
          stat    = "Average"
          period  = 60
          metrics = local.ecs_cpu_metrics
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 12
        width  = 12
        height = 6
        properties = {
          title   = "ECS — Memory Utilization (%)"
          region  = var.region
          view    = "timeSeries"
          stat    = "Average"
          period  = 60
          metrics = local.ecs_mem_metrics
        }
      },
      # ---- Row 3: RDS ---------------------------------------------------------------------------------------------
      {
        type   = "metric"
        x      = 0
        y      = 18
        width  = 8
        height = 6
        properties = {
          title  = "RDS — CPU Utilization (%)"
          region = var.region
          view   = "timeSeries"
          stat   = "Average"
          period = 60
          metrics = [
            ["AWS/RDS", "CPUUtilization", "DBInstanceIdentifier", var.rds_instance_id]
          ]
        }
      },
      {
        type   = "metric"
        x      = 8
        y      = 18
        width  = 8
        height = 6
        properties = {
          title  = "RDS — Database Connections"
          region = var.region
          view   = "timeSeries"
          stat   = "Average"
          period = 60
          metrics = [
            ["AWS/RDS", "DatabaseConnections", "DBInstanceIdentifier", var.rds_instance_id]
          ]
        }
      },
      {
        type   = "metric"
        x      = 16
        y      = 18
        width  = 8
        height = 6
        properties = {
          title  = "RDS — Free Storage Space (bytes)"
          region = var.region
          view   = "timeSeries"
          stat   = "Average"
          period = 60
          metrics = [
            ["AWS/RDS", "FreeStorageSpace", "DBInstanceIdentifier", var.rds_instance_id]
          ]
        }
      }
    ]
  }
}

resource "aws_cloudwatch_dashboard" "this" {
  dashboard_name = "${var.name_prefix}-overview"
  dashboard_body = jsonencode(local.dashboard_body)
}
