# ---------------------------------------------------------------------------------------------------------------------
# COMMON GITHUB OIDC CONFIGURATION
# Wraps the repo-local _modules/github-oidc. account_id / region come from the global inputs generated by root.hcl.
# ---------------------------------------------------------------------------------------------------------------------

locals {
  env_vars  = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  live_root = dirname(find_in_parent_folders("root.hcl"))
}

terraform {
  source = "${local.live_root}/../../modules/aws//iam"
}

# aws_region / account_id / tags are injected globally by root.hcl's `inputs`, so they are not repeated here.
inputs = {
  name        = "sgcut-${local.env_vars.locals.environment}-gha-app-deploy"
  github_repo = local.env_vars.locals.github_repo

  # Two-role split for the infra (Terragrunt) workflow: a broad apply role trusted only on main, and a
  # read-only plan role trusted on PRs (which run PR-controlled workflow code) — see modules/aws/iam.
  create_infra_role    = true
  infra_role_name      = "sgcut-${local.env_vars.locals.environment}-gha-infra-all-rw"
  infra_plan_role_name = "sgcut-${local.env_vars.locals.environment}-gha-infra-all-ro"

  # Static-credential user for the LOCAL bootstrap (run via `task bootstrap`, not CI). It manages this very unit +
  # the state backend, out-of-band of OIDC. Its access key is generated in the console and used locally — never in
  # TF state, never in GitHub Secrets.
  create_bootstrap_user = true
  bootstrap_user_name   = "sgcut-${local.env_vars.locals.environment}-gha-infra-admin-user"
}
